### PR TITLE
Default token to GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by tcbyrd**
See https://github.com/paper-spa/deploy-pages/pull/2 and https://github.com/github/github/pull/200003 for the other side of this.

### CODE REVIEW

**Review by YiMysty — APPROVED** [review]
nice~~

**Comment by tcbyrd** [comment]
@jriggins Seems like this is failing maybe because Jekyll is trying to evaluate what's in the `${{ }}` in the `action.yml`? I'm not totally following why that test cares, since the test projects are in a sub-folder. Thoughts?

**Comment by jriggins** [comment]
> @jriggins Seems like this is failing maybe because Jekyll is trying to evaluate what's in the `${{ }}` in the `action.yml`? I'm not totally following why that test cares, since the test projects are in a sub-folder. Thoughts?

@tcbyrd I believe that I had tried this in my early dev of this and it failed. I believe it's because `secrets` is not available in the action definition file. [This](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) is what all that I believe that is.

**Comment by tcbyrd** [comment]
Apparently `${{ github.token }}` is what's needed: https://github.com/paper-spa/deploy-pages/pull/2/commits/3ffe3310eb60162c51c0e78b9e1c64213369a706

Fixed in a094653

**Pull request merged**
